### ISSUE TITLE
httpOnly

### ISSUE THREAD

**Issue by berrg** [Tarang11/fastify-csrf#8]
Why is not httpOnly set on the coockie? In order to protect against csrf the coockie should not be readable by javascript. How does this lib protect against csrf without this?

**Comment by Tarang11** [comment]
fastify-csrf just verify token, other options related with cookie and its behavior should be set on plugin responsible for cookie.

**Comment by Tarang11** [comment]
fastify-csrf can be cookie based or session. As per your issue, perhaps you are using cookie based validation. Default option for cookie based validation are { key: '_csrf', path: '/' }, but in you case you want it be be httpOnly as well. So use { cookie: { /* your cookie behaviour */ } instead of { cookie: true } in fastify-csrf.
